#!/usr/bin/env bash

# Ex: ./deployCDN -p 20200 -o cs5700cdnorigin.ccs.neu.edu:8080  -u bitbusters -n cs5700cdn.example.com -i ~/.ssh/id_rsa

# Include command-line options from cdnOptions.sh
source $(dirname $0)/cdnOptions.sh

# Helper function to deploy files to the given server server
# Usage: deploy script hostname
function deploy {
  script=$1
  hostname=$2
  echo "Deploying to $hostname ..."
  mkdir ./pkg
  for file in "${files[@]}"
  do
    cp $file ./pkg
  done
  scp $ssh_options -i $keyfile -r $(dirname $0)/pkg/* $username@$hostname:/home/$username
  ssh $ssh_options -i $keyfile $username@$hostname "make $script"
  rm -rf pkg
}

# Deploy files to the DNS server
deploy dnsserver 'cdn-dns.5700.network'

# Deploy files to the HTTP servers from the replicas array
for value in "${replicas[@]}"
do
  deploy httpserver $value
done